export const GameState = Object.freeze({
  MENU: "MENU",
  PLAYING: "PLAYING",
  PAUSED: "PAUSED",
  UPGRADING: "UPGRADING",
  GAME_OVER: "GAME_OVER",
  LEADERBOARD_LOADING: "LEADERBOARD_LOADING",
});
