var SHEET_NAME='Leaderboard',HEADERS=['Timestamp','Username','Score','Distance','DurationMs','MaxCombo','TargetsDestroyed','GameVersion'];
function doGet(e){try{var a=String(e&&e.parameter&&e.parameter.action||'top');if(a==='health')return json_({ok:true,status:'healthy'});if(a!=='top')return json_({ok:false,error:'Unsupported action'});var l=Math.min(10,Math.max(1,int_(e.parameter.limit,10))),s=sheet_(),r=s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,HEADERS.length).getValues(),b={};r.forEach(function(x){var u=username_(x[1]),n=Number(x[2]);if(u&&Number.isFinite(n)&&n>=0&&Number.isInteger(n))b[u]=Math.max(b[u]||0,n)});var scores=Object.keys(b).map(function(u){return{username:u,score:b[u]}});scores.sort(function(x,y){return y.score-x.score||x.username.localeCompare(y.username)});return json_({ok:true,scores:scores.slice(0,l)})}catch(_){return json_({ok:false,error:'Request failed'})}}
function doPost(e){var l=LockService.getScriptLock();try{l.waitLock(5000);var p=e&&e.parameter||{},u=username_(p.username),s=bound_(p.score,100000000),d=bound_(p.distance,10000000),t=bound_(p.durationMs,86400000),c=bound_(p.maxCombo,100000),g=bound_(p.targetsDestroyed,1000000),v=safe_(String(p.gameVersion||'').slice(0,20));if(!u||[s,d,t,c,g].some(function(x){return x===null})||!v)return json_({ok:false,error:'Invalid submission'});if(s>Math.max(5000,t*2)||d>t/5+1000)return json_({ok:false,error:'Implausible submission'});sheet_().appendRow([new Date(),safe_(u),s,d,t,c,g,v]);return json_({ok:true})}catch(_){return json_({ok:false,error:'Request failed'})}finally{try{l.releaseLock()}catch(_){}}}
function sheet_(){var ss=SpreadsheetApp.getActiveSpreadsheet(),s=ss.getSheetByName(SHEET_NAME)||ss.insertSheet(SHEET_NAME);if(s.getLastRow()===0)s.appendRow(HEADERS);return s}
function username_(v){var s=String(v||'').trim();return/^[A-Za-z0-9_-]{3,16}$/.test(s)?s:''}
function int_(v,f){var n=Number(v);return Number.isFinite(n)&&Number.isInteger(n)?n:f}
function bound_(v,m){var n=Number(v);return Number.isFinite(n)&&Number.isInteger(n)&&n>=0&&n<=m?n:null}
function safe_(v){var s=String(v||'');return/^[=+\-@]/.test(s)?"'"+s:s}
function json_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON)}
